# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mash ncbi-blast+ libcurl4-openssl-dev libssl-dev python3-pip python3-dev python3-numpy python3-pandas -y
        python3 -m pip install --upgrade pip setuptools
        pip3 install pytest Cython
        if [ -f requirements.txt ]; then 
          pip3 install -r requirements.txt;
        else
          pip3 install -e .
        fi
    - name: Test  with pytest
      run: |
        pytest -o log_cli=true --basetemp=tmp-pytest
